### ISSUE TITLE
Replace `ME_CONFIG_MONGODB_SERVER` with `ME_CONFIG_MONGODB_URL`

### ISSUE THREAD

**Issue by rtritto** [mongo-express/mongo-express-docker#113]
Environment variables `ME_CONFIG_MONGODB_SERVER` and `ME_CONFIG_MONGODB_PORT` were removed (in favor of `ME_CONFIG_MONGODB_URL`) in https://github.com/mongo-express/mongo-express/pull/957.
The retry logic introduced in #43 use the environment variables `ME_CONFIG_MONGODB_SERVER` and `ME_CONFIG_MONGODB_PORT` and needs to be replaced with `ME_CONFIG_MONGODB_URL`.

**Comment by BlackthornYugen** [comment]
Is this bug also related to why $host isn't getting set correctly? 

![image](https://github.com/mongo-express/mongo-express-docker/assets/3138467/d01f350f-d8a0-4ea8-a730-381760ced1d8)

**Comment by BlackthornYugen** [comment]
If I set both `ME_CONFIG_MONGODB_SERVER` and `ME_CONFIG_MONGODB_URL` it's fine though. 

```yaml
version: '3.3'

services:
    mongo:
        image: mongo:4

    mongoexpress:
        image: mongo-express:latest
        ports:
            - "8081:8081"
        links:
            - mongo
        environment: 
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
```

![image](https://github.com/mongo-express/mongo-express-docker/assets/3138467/df1960c0-9511-4a5a-b5ca-5b603f21a585)

**Comment by BlackthornYugen** [comment]
I can make a PR later to put something like this in the entrypoint:

```bash
extract_host() {
    local url="$1"
    local host_with_port=${url#mongodb://*}  # Remove 'mongodb://' prefix
    local host=${host_with_port%%:*}         # Extract up to the first colon
    echo "${host%%,*}"                       # Extract up to the first comma if present
}
```

**Comment by rtritto** [comment]
> Is this bug also related to why $host isn't getting set correctly?
> 
> ![image](https://private-user-images.githubusercontent.com/3138467/294713490-d01f350f-d8a0-4ea8-a730-381760ced1d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1ODkzMTksIm5iZiI6MTcwNDU4OTAxOSwicGF0aCI6Ii8zMTM4NDY3LzI5NDcxMzQ5MC1kMDFmMzUwZi1kOGEwLTRlYTgtYTczMC0zODE3NjBjZWQxZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMDA1NjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTA2MTFhZDg5OWM0YzE0ZmM0ZjU2MTVlYjhhZWFkYzQwOGI2NWU0MjhmZTdhNGYzMmY1N2ZkOTExNGZlZTUwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UkqA8DHyOtSSJcnHd9S8zzgUC5pCa4gFIHs9DpAsjxI)

@BlackthornYugen it's fixed by #70.

`ME_CONFIG_MONGODB_SERVER` it's not valid (deprecated/unsafe old logic) because it's removed in https://github.com/mongo-express/mongo-express/pull/957.
`ME_CONFIG_MONGODB_URL` is a required env var, in `docker-entrypoint.sh` we can prefer to add a check to verify if it's missing or not valid.

**Comment by SchrodingersCpp** [comment]
`ME_CONFIG_MONGODB_URL` is still not mentioned on the [Docker Hub mongo-express page](https://hub.docker.com/_/mongo-express).
